# Generated by Django 5.2.6 on 2025-09-21 14:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=7)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('recommended_crop', models.CharField(blank=True, max_length=100)),
                ('probabilities', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
