# Generated by Django 5.2.6 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropinput',
            name='features',
            field=models.TextField(),
        ),
    ]
