# Generated by Django 5.2.6 on 2025-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_alter_cropinput_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropinput',
            name='features',
            field=models.JSONField(),
        ),
    ]
