# Generated by Django 5.2.6 on 2025-09-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_alter_cropinput_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropinput',
            old_name='soil_type',
            new_name='soilType',
        ),
    ]
